export type RootStackParams = {
  onboarding: undefined;
  signUp: undefined;
  login: undefined;
  homepage: undefined;
  bottomTab: undefined;
  popularDocFullPage: undefined;
  appointmentPage: undefined;
  appointmentSchedulePage: undefined;
  docdetails: undefined;
  favoriteDocPage: undefined;
  drawerTab: undefined;
  myDoctorPage: undefined;
  medicalRecordPage: undefined;
  paymentPage: undefined;
  medicineOrderPage: undefined;
  testBookingPage: undefined;
  privacyAndPolicyPage: undefined;
  helpCenterPage: undefined;
  settingPage: undefined;
};
